Tea 43
bondloong/teamwork_01_project pull request #29
Opened 2024-06-24 10:50 UTC by sjakaev

### Какую задачу решаем
#### Добавить в проект MEMORYLEAKS.md, в котором описаны, какие утечки были и как они исправлены

- В случае, если утечек не было, также написать об этом и приложить отчёт с текущим результатом.
- Использовать useMemo, useCallback, React.memo (можно использовать React Dev Tools)
- На утечки стоит профилировать только саму страницу игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-25 10:51 UTC, rizespb approved these changes

2024-06-25 10:51 UTC, rizespb commented on packages/client/src/widgets/Game/ui/Game/GameOverModal/GameOverModal.tsx
> +  const NavigateToMain = useCallback((): void => {
```suggestion
  const navigateMain = useCallback((): void => {
```

2024-06-25 13:38 UTC, IvanPeleshok requested changes
Добрый день

Предлагаю ознакомиться с комментариями и доработать неточности

Хорошего дня :)

2024-06-25 13:38 UTC, IvanPeleshok commented on packages/client/src/widgets/Game/ui/Game/Game.tsx
> +    if (animationId.current) {
В теле компоненты такие условия приведут к тому, что при каждой перерисовке будет проверяться условие, что не кажется оптимальным

Возможно вынести на уровнь useEffect и поставить нужный список зависимостей для отмены анимации?

2024-06-25 13:38 UTC, IvanPeleshok commented on packages/client/src/widgets/Game/ui/Game/GameOverModal/GameOverModal.tsx
> +  }, [onClose]);
Каждый раз, когда меняется компонент выше по иерархии и обновляются пропсы - будет пересоздаваться handler вызывая под копотом реализацию useCallback, что в итоге может утяжелить выполнения кода

Если хотите, что данный кейс работал, то необходимо обернуть компонент в `memo`, а так-же onClose в useCallback, чтобы при ререндере родительского компонента не пересоздавалась ссылка в памяти

2024-06-25 13:38 UTC, IvanPeleshok commented on packages/client/src/widgets/Game/ui/Game/GameOverModal/GameOverModal.tsx
> +  }, [navigate]);
Для какой цели добавили navigate в список зависимостей? (по ощущениям, его можно оставить пустым)

2024-06-25 13:38 UTC, IvanPeleshok commented on packages/client/src/widgets/Game/ui/Game/Game.tsx
> +      audio.current.gameOverAudio?.play().catch((error) => console.error(error));
Здорово, что обработали исключение

2024-06-25 13:38 UTC, IvanPeleshok commented on MEMORYLEAKS.md
Было бы здорово увидеть какое-то графическое представление из devtools (скрин до и после)

2024-06-25 16:04 UTC, sjakaev commented on packages/client/src/widgets/Game/ui/Game/GameOverModal/GameOverModal.tsx
> +  }, [navigate]);
да, можно оставить пустым, спасибо за подсказку

2024-06-25 16:04 UTC, sjakaev commented on packages/client/src/widgets/Game/ui/Game/Game.tsx
> +    if (animationId.current) {
хорошая идея, поправил

2024-06-25 16:05 UTC, sjakaev commented on packages/client/src/widgets/Game/ui/Game/GameOverModal/GameOverModal.tsx
> +  }, [onClose]);
ух, да, согласен. поправил, спасибо)

2024-06-25 16:05 UTC, sjakaev commented on MEMORYLEAKS.md
добавил, там и правда виден результат 👍

2024-06-26 15:23 UTC, IvanPeleshok approved these changes
Добрый день!
Отличная работа, продолжайте в том же духе :)
Поздравляю, апрув 🎉

2024-06-26 15:23 UTC, IvanPeleshok commented on MEMORYLEAKS.md
> +Функции `handleClose` и `NavigateToMain`, используемые в обработчиках событий, создавались заново при каждом рендере, что приводило к избыточным вычислениям.
Вычисления избыточные не происходили, создавались новые объекты в памяти

2024-06-26 15:23 UTC, IvanPeleshok commented on MEMORYLEAKS.md
> +Компонент `GameOverModal` был обёрнут в `React.memo`, а функции `handleClose` и `navigateMain` были обёрнуты в `useCallback`:
Спорная оптимизация, но для практики полезно)

2024-06-26 16:25 UTC, merged