Tea 47
bondloong/teamwork_01_project pull request #41
Opened 2024-07-12 10:17 UTC by Mizou9999

### Какую задачу решаем
https://linear.app/teamwork-01-project/issue/TEA-47/pereklyuchenie-temy-bekend
https://linear.app/teamwork-01-project/issue/TEA-46/pereklyuchenie-tem-klientskaya-chast
### Скриншоты/видяшка (если есть)
![image](https://github.com/user-attachments/assets/4d5d4d7d-46c3-485d-924a-2fa3f23d313a)
![image](https://github.com/user-attachments/assets/de21aee1-6432-4f2e-9035-16907a00ba00)

### TBD (если есть)

2024-07-13 09:31 UTC, sjakaev commented on packages/client/src/entities/User/api/setTheme/setTheme.tsx
> +      console.log('Payload:', thunkAPI);
консоль лог можно убрать

2024-07-13 09:42 UTC, sjakaev approved these changes

2024-07-13 09:43 UTC, sjakaev commented on packages/server/controllers/userController.ts
> +  console.log('Received request body:', req.body);
и тут тоже можно убрать консоль

2024-07-13 22:17 UTC, IvanPeleshok requested changes
Отличная работа, особенно радует обработка исключений, как на фронте, так и на стороне сервера

Есть пара мелких замечаний и вопрос
Предлагаю ознакомиться и поправить

Хорошего дня :)

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/entities/User/api/fetchTheme/fetchTheme.tsx
> +  async (userId, thunkApi) => {
```
async (userId, { rejectWithValue }) =>

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
> +  currentTheme: 'light',
Предлагаю вынести light / dark в константы и переиспользовать их (встречается неоднократно)

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
> +    if (user && user.id) {
```
if (user?.id)

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
> +      dispatch(fetchTopicAuthor(user.id))
Предлагаю воспользоваться последним синтаксисом работы с промисами async / await + try / catch
```
try {
  const response = async dispatch(fetchTopicAuthor(user.id)).unwrap()
  setAuthorId(response.id)
} catch (ex) {
   // handle ex
}
```
Читается получше

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
> +      dispatch(fetchTheme(authorId))
Аналогично

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
> +    const newTheme = currentTheme === 'light' ? 'dark' : 'light';
Берём из констант

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
Не заметил работы с `localStorage`, чтобы мы могли предустанавливать тему без запроса, если она ранее менялась и не было морганий на время запроса

Ошибаюсь и она не требуется?

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/widgets/ThemeSwtich/ui/ThemeSwitch/ThemeSwitch.interfaces.tsx
> +  id: string | undefined;
id?: string

2024-07-13 22:17 UTC, IvanPeleshok commented on packages/client/src/widgets/ThemeSwtich/ui/ThemeSwitch/ThemeSwitch.tsx
> +        checked={currentTheme === 'dark'}
Из константы

2024-07-15 09:11 UTC, Mizou9999 commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
добавил логику для localStorage

2024-07-16 07:10 UTC, IvanPeleshok approved these changes
Добрый день
Всё замечательно
Поздравляю, апрув 🚀 

Хорошего дня :)

2024-07-16 07:10 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/theme/themeProvider.tsx
> +          localStorage.setItem('theme', theme as ThemeName);
Можно бы было вынести в отдельный сервис

2024-07-17 07:06 UTC, bondloong approved these changes

2024-07-17 08:35 UTC, merged