Эмодзи (клиентская часть)
bondloong/teamwork_01_project pull request #42
Opened 2024-07-13 07:54 UTC by sjakaev

### Какую задачу решаем
Добавлена возможность оставлять emoji реакции на комментарии к постам ( клиентская часть )
https://linear.app/teamwork-01-project/issue/TEA-14/emodzi-klientskaya-chast

### Скриншоты/видяшка (если есть)
![image](https://github.com/user-attachments/assets/66b0518b-09fa-412c-9895-4a95408110bb)

### TBD (если есть)

2024-07-13 08:20 UTC, bondloong approved these changes

2024-07-13 09:54 UTC, Mizou9999 commented on packages/client/src/widgets/TopicComment/ui/TopicComment/TopicComment.module.scss
> +  background-color: #f8f8f8;
может здесь лучше --color-bg-base (чтобы правильно работало с dark/light theme)

2024-07-13 22:07 UTC, IvanPeleshok requested changes
Добрый день

Отличная работа
Оставил пару комментариев и вопрос
Предлагаю ознакомиться и поправить :)

Так же есть неисправленные замечания ваших сокомандников

2024-07-13 22:07 UTC, IvanPeleshok commented on packages/client/src/entities/Topics/model/slice/topicsSlice.ts
> +      const topic = state.data.find((topic) => topic.id === payload.topicId);
```
find({ id }) => id == ...

2024-07-13 22:07 UTC, IvanPeleshok commented on packages/client/src/entities/Topics/model/slice/topicsSlice.ts
> +      { payload }: PayloadAction<{ commentId: string; reaction: EReactions }>
EReactions - предлагаю не сокращать названия, т.к код пишется для таких же разработчиков и могут возникать вопросы

2024-07-13 22:07 UTC, IvanPeleshok commented on packages/client/src/features/ReactionEmojiPicker/ui/SelectedEmojis/SelectedEmojis.tsx
> +  const memoizedReactions = useMemo(() => reactions, [reactions]);
А будет ли оптимизация для данного кейса, ведь reactions сам по себе будет пересоздаваться столько же раз, сколько и memoizedReactions (ошибаюсь?)

2024-07-13 22:07 UTC, IvanPeleshok commented on packages/client/src/widgets/TopicComment/ui/TopicComment/TopicComment.module.scss
> +    background-color: #f3f3f3;
Члены вашей команды оставляли комментарии относительно переменных цветов для темы
Предлагаю воспользоваться ими

2024-07-13 22:07 UTC, IvanPeleshok commented on packages/client/src/entities/Topics/model/types/topic.ts
> +  commentsReactions: { [key: string]: EReactions[] };
Record<string, EReactions[]>

2024-07-14 08:09 UTC, sjakaev commented on packages/client/src/features/ReactionEmojiPicker/ui/SelectedEmojis/SelectedEmojis.tsx
> +  const memoizedReactions = useMemo(() => reactions, [reactions]);
Да, ты прав) `useSelector` с `shallowEqual` уже сами по себе сравнивает старое и новое значения и предотвращает ререндер, если данные не изменились. `useMemo` тут не нужен

2024-07-14 08:15 UTC, sjakaev commented on packages/client/src/widgets/TopicComment/ui/TopicComment/TopicComment.module.scss
> +  background-color: #f8f8f8;
твой пр с темами пока не в ветке `main`, поэтому я не могу заюзать `--color-bg-base` ((
давай пока заменю на существующую переменную - `$primary-bg-color`, а когда в ветку `main` будем сливать наши пр, то уже посмотрим, чтобы не было конфликтов и с темной темой норм смотрелось?

2024-07-14 08:19 UTC, sjakaev commented on packages/client/src/widgets/TopicComment/ui/TopicComment/TopicComment.module.scss
> +    background-color: #f3f3f3;
пр с темами пока не в ветке `main`, поэтому я не могу тут использовать переменные темизации. но я могу использовать существующие переменные - `$primary-bg-color`, `$secondary-color`, а уже во время слияния наших веток в метку `main` поправить конфликты, которые будут и посмотреть чтобы хорошо смотрелось с темной темой

2024-07-14 10:36 UTC, IvanPeleshok approved these changes
Всё супер
Поздравляю, апрув 🚀 
Хорошего дня :)

2024-07-14 10:55 UTC, merged